presidents = [
    {
        "id": 1,
        "ordinal": 1,
        "name": "George Washington",
        "yearsInOffice": "1789-1797",
        "vicePresidents": ["John Adams"],
        "photo": "https://presidents-memory.netlify.app/presidents/1.png",
    },
    {
        "id": 2,
        "ordinal": 2,
        "name": "John Adams",
        "yearsInOffice": "1797-1801",
        "vicePresidents": ["Thomas Jefferson"],
        "photo": "https://presidents-memory.netlify.app/presidents/2.png",
    },
    {
        "id": 3,
        "ordinal": 3,
        "name": "Thomas Jefferson",
        "yearsInOffice": "1801-1809",
        "vicePresidents": ["Aaron Burr", "George Clinton"],
        "photo": "https://presidents-memory.netlify.app/presidents/3.png",
    },
    {
        "id": 4,
        "ordinal": 4,
        "name": "James Madison",
        "yearsInOffice": "1809-1817",
        "vicePresidents": ["George Clinton", "Elbr'id'ge Gerry"],
        "photo": "https://presidents-memory.netlify.app/presidents/4.png",
    },
    {
        "id": 5,
        "ordinal": 5,
        "name": "James Monroe",
        "yearsInOffice": "1817-1825",
        "vicePresidents": ["Daniel D. Tompkins"],
        "photo": "https://presidents-memory.netlify.app/presidents/5.png",
    },
    {
        "id": 6,
        "ordinal": 6,
        "name": "John Quincy Adams",
        "yearsInOffice": "1825-1829",
        "vicePresidents": ["John C. Calhoun"],
        "photo": "https://presidents-memory.netlify.app/presidents/6.png",
    },
    {
        "id": 7,
        "ordinal": 7,
        "name": "Andrew Jackson",
        "yearsInOffice": "1829-1837",
        "vicePresidents": ["John C. Calhoun", "Martin Van Buren"],
        "photo": "https://presidents-memory.netlify.app/presidents/7.png",
    },
    {
        "id": 8,
        "ordinal": 8,
        "name": "Martin Van Buren",
        "yearsInOffice": "1837-1841",
        "vicePresidents": ["Richard Mentor Johnson"],
        "photo": "https://presidents-memory.netlify.app/presidents/8.png",
    },
    {
        "id": 9,
        "ordinal": 9,
        "name": "William Henry Harrison",
        "yearsInOffice": "1841",
        "vicePresidents": ["John Tyler"],
        "photo": "https://presidents-memory.netlify.app/presidents/9.png",
    },
    {
        "id": 10,
        "ordinal": 10,
        "name": "John Tyler",
        "yearsInOffice": "1841-1845",
        "vicePresidents": ["None"],
        "photo": "https://presidents-memory.netlify.app/presidents/10.png",
    },
    {
        "id": 11,
        "ordinal": 11,
        "name": "James K. Polk",
        "yearsInOffice": "1845-1849",
        "vicePresidents": ["George M. Dallas"],
        "photo": "https://presidents-memory.netlify.app/presidents/11.png",
    },
    {
        "id": 12,
        "ordinal": 12,
        "name": "Zacary Taylor",
        "yearsInOffice": "1849-1850",
        "vicePresidents": ["Millard Fillmore"],
        "photo": "https://presidents-memory.netlify.app/presidents/12.png",
    },
    {
        "id": 13,
        "ordinal": 13,
        "name": "Millard Fillmore",
        "yearsInOffice": "1850-1853",
        "vicePresidents": ["None"],
        "photo": "https://presidents-memory.netlify.app/presidents/13.png",
    },
    {
        "id": 14,
        "ordinal": 14,
        "name": "Franklin Pierce",
        "yearsInOffice": "1853-1857",
        "vicePresidents": ["William R. King"],
        "photo": "https://presidents-memory.netlify.app/presidents/14.png",
    },
    {
        "id": 15,
        "ordinal": 15,
        "name": "James Buchanan",
        "yearsInOffice": "1857-1861",
        "vicePresidents": ["John C. Breckinr'id'ge"],
        "photo": "https://presidents-memory.netlify.app/presidents/15.png",
    },
    {
        "id": 16,
        "ordinal": 16,
        "name": "Abraham Lincoln",
        "yearsInOffice": "1861-1865",
        "vicePresidents": ["Hannibal Hamlin", "Andrew John"],
        "photo": "https://presidents-memory.netlify.app/presidents/16.png",
    },
    {
        "id": 17,
        "ordinal": 17,
        "name": "Andrew Johnson",
        "yearsInOffice": "1865-1869",
        "vicePresidents": ["None"],
        "photo": "https://presidents-memory.netlify.app/presidents/17.png",
    },
    {
        "id": 18,
        "ordinal": 18,
        "name": "Ulysses S. Grant",
        "yearsInOffice": "1869-1877",
        "vicePresidents": ["Schuyler Colfax", "Henry Wilson"],
        "photo": "https://presidents-memory.netlify.app/presidents/18.png",
    },
    {
        "id": 19,
        "ordinal": 19,
        "name": "Rutherford B. Hayes",
        "yearsInOffice": "1877-1881",
        "vicePresidents": ["William A. Wheeler"],
        "photo": "https://presidents-memory.netlify.app/presidents/19.png",
    },
    {
        "id": 20,
        "ordinal": 20,
        "name": "James A. Garfield",
        "yearsInOffice": "1881",
        "vicePresidents": ["Chester A. Arthur"],
        "photo": "https://presidents-memory.netlify.app/presidents/20.png",
    },
    {
        "id": 21,
        "ordinal": 21,
        "name": "Chester A. Arthur",
        "yearsInOffice": "1881-1885",
        "vicePresidents": ["None"],
        "photo": "https://presidents-memory.netlify.app/presidents/21.png",
    },
    {
        "id": 22,
        "ordinal": 22,
        "name": "Grover Cleveland",
        "yearsInOffice": "1893-1897",
        "vicePresidents": ["Adlai Stevenson I"],
        "photo": "https://presidents-memory.netlify.app/presidents/22.png",
    },
    {
        "id": 23,
        "ordinal": 23,
        "name": "Benjamin Harrison",
        "yearsInOffice": "1889-1893",
        "vicePresidents": ["Levi P. Morton"],
        "photo": "https://presidents-memory.netlify.app/presidents/23.png",
    },
    {
        "id": 24,
        "ordinal": 24,
        "name": "Grover Cleveland",
        "yearsInOffice": "1893-1897",
        "vicePresidents": ["Adlai Stevenson I"],
        "photo": "https://presidents-memory.netlify.app/presidents/24.png",
    },
    {
        "id": 25,
        "ordinal": 25,
        "name": "William McKinley",
        "yearsInOffice": "1897-1901",
        "vicePresidents": ["Garret Hobart", "Theodore Roosevelt"],
        "photo": "https://presidents-memory.netlify.app/presidents/25.png",
    },
    {
        "id": 26,
        "ordinal": 26,
        "name": "Theodore Roosevelt",
        "yearsInOffice": "1901-1909",
        "vicePresidents": ["Charles W. Fairbanks"],
        "photo": "https://presidents-memory.netlify.app/presidents/26.png",
    },
    {
        "id": 27,
        "ordinal": 27,
        "name": "William Howard Taft",
        "yearsInOffice": "1909-1913",
        "vicePresidents": ["James S. Sherman"],
        "photo": "https://presidents-memory.netlify.app/presidents/27.png",
    },
    {
        "id": 28,
        "ordinal": 28,
        "name": "Woodrow Wilson",
        "yearsInOffice": "1913-1921",
        "vicePresidents": ["Thomas R. Marshall"],
        "photo": "https://presidents-memory.netlify.app/presidents/28.png",
    },
    {
        "id": 29,
        "ordinal": 29,
        "name": "Warren G. Harding",
        "yearsInOffice": "1921-1923",
        "vicePresidents": ["Calvin Cool'id'ge"],
        "photo": "https://presidents-memory.netlify.app/presidents/29.png",
    },
    {
        "id": 30,
        "ordinal": 30,
        "name": "Calvin Cool'id'ge",
        "yearsInOffice": "1923-1925",
        "vicePresidents": ["Charles G. Dawes"],
        "photo": "https://presidents-memory.netlify.app/presidents/30.png",
    },
    {
        "id": 31,
        "ordinal": 31,
        "name": "Herbert Hoover",
        "yearsInOffice": "1929-1933",
        "vicePresidents": ["Charles Curtis"],
        "photo": "https://presidents-memory.netlify.app/presidents/31.png",
    },
    {
        "id": 32,
        "ordinal": 32,
        "name": "Franklin D. Roosevelt",
        "yearsInOffice": "1933-1945",
        "vicePresidents": ["John N. Garner", "Henry A. Wallace", "Harry S. Truman"],
        "photo": "https://presidents-memory.netlify.app/presidents/32.png",
    },
    {
        "id": 33,
        "ordinal": 33,
        "name": "Harry S. Truman",
        "yearsInOffice": "1945-1953",
        "vicePresidents": ["Alben W. Barkley"],
        "photo": "https://presidents-memory.netlify.app/presidents/33.png",
    },
    {
        "id": 34,
        "ordinal": 34,
        "name": "Dwight D. Eisenhower",
        "yearsInOffice": "1953-1961",
        "vicePresidents": ["Richard Nixon"],
        "photo": "https://presidents-memory.netlify.app/presidents/34.png",
    },
    {
        "id": 35,
        "ordinal": 35,
        "name": "John F. Kennedy",
        "yearsInOffice": "1961-1963",
        "vicePresidents": ["Lyndon B. Johnson"],
        "photo": "https://presidents-memory.netlify.app/presidents/35.png",
    },
    {
        "id": 36,
        "ordinal": 36,
        "name": "Lyndon B. Johnson",
        "yearsInOffice": "1963-1969",
        "vicePresidents": ["Hubert Humphrey"],
        "photo": "https://presidents-memory.netlify.app/presidents/36.png",
    },
    {
        "id": 37,
        "ordinal": 37,
        "name": "Richard Nixon",
        "yearsInOffice": "1969-1974",
        "vicePresidents": ["Spiro Agnew", "Gerald Ford"],
        "photo": "https://presidents-memory.netlify.app/presidents/37.png",
    },
    {
        "id": 38,
        "ordinal": 38,
        "name": "Gerald Ford",
        "yearsInOffice": "1974-1977",
        "vicePresidents": ["Nelson Rockefeller"],
        "photo": "https://presidents-memory.netlify.app/presidents/38.png",
    },
    {
        "id": 39,
        "ordinal": 39,
        "name": "Jimmy Carter",
        "yearsInOffice": "1977-1981",
        "vicePresidents": ["Walter Mondale"],
        "photo": "https://presidents-memory.netlify.app/presidents/39.png",
    },
    {
        "id": 40,
        "ordinal": 40,
        "name": "Ronald Reagan",
        "yearsInOffice": "1981-1989",
        "vicePresidents": ["George H.W. Bush"],
        "photo": "https://presidents-memory.netlify.app/presidents/40.png",
    },
    {
        "id": 41,
        "ordinal": 41,
        "name": "George H. W. Bush",
        "yearsInOffice": "1989-1993",
        "vicePresidents": ["Dan Quayle"],
        "photo": "https://presidents-memory.netlify.app/presidents/41.png",
    },
    {
        "id": 42,
        "ordinal": 42,
        "name": "Bill Clinton",
        "yearsInOffice": "1993-2001",
        "vicePresidents": ["Al Gore"],
        "photo": "https://presidents-memory.netlify.app/presidents/42.png",
    },
    {
        "id": 43,
        "ordinal": 43,
        "name": "George W. Bush",
        "yearsInOffice": "2001-2009",
        "vicePresidents": ["Dick Cheney"],
        "photo": "https://presidents-memory.netlify.app/presidents/43.png",
    },
    {
        "id": 44,
        "ordinal": 44,
        "name": "Barack Obama",
        "yearsInOffice": "2009-2017",
        "vicePresidents": ["Joe B'id'en"],
        "photo": "https://presidents-memory.netlify.app/presidents/44.png",
    },
    {
        "id": 45,
        "ordinal": 45,
        "name": "Donald Trump",
        "yearsInOffice": "2017-2021",
        "vicePresidents": ["Mike Pence"],
        "photo": "https://presidents-memory.netlify.app/presidents/45.png",
    },
    {
        "id": 46,
        "ordinal": 46,
        "name": "Joe B'id'en",
        "yearsInOffice": "2021-present",
        "vicePresidents": ["Kamala Harris"],
        "photo": "https://presidents-memory.netlify.app/presidents/46.png",
    },
]
